CREATE TABLE CAMPANHA (ID BIGINT IDENTITY(1,1) PRIMARY KEY ,
						NOME VARCHAR(255),
					 	DELETADO BOOLEAN,
					 	DATACADASTRO BIGINT,
					 	IDTIMEDOCORACAO BIGINT,
					 	INICIOVIGENCIA BIGINT,
					 	TERMINOVIGENCIA BIGINT
					 	);